name: Gradle Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.2

      - name: Setup Java JDK
        uses: graalvm/setup-graalvm@main
        with:
          java-version: 17
          distribution: graalvm

      - name: Setup Gradle
        uses: gradle/gradle-build-action@main

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@main

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build artifacts
        run: ./gradlew build --no-daemon --stacktrace

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: CE Test Build
          path: |
            build/jars
          compression-level: 9

      - name: Generate Build Summary
        uses: actions/github-script@main
        with:
          script: |
            const { owner, repo } = context.repo;
            const run_id = context.runId;
            core.summary
              .write();